---
- name: remove the iis web service
  hosts: windows

  tasks:
   - name: stop iis service
     win_service:
       name: W3Svc
       state: stopped

   - name: remove iis
     win_feature:
       name: Web-Server
       state: present

   - name: remove index.html
     win_file:
       path: C:\Inetpub\wwwroot\index.html
       state: absent
