---
- name: remove the iis web service
  hosts: windows

  tasks:
   - name: stop iis service
     ansible.windows.win_service:
       name: W3Svc
       state: stopped

   - name: remove iis
     ansible.windows.win_feature:
       name: Web-Server
       state: present

   - name: remove index.html
     ansible.windows.win_file:
       path: C:\Inetpub\wwwroot\index.html
       state: absent
