---
- name: playbook template
  hosts: "{{ satellite_group_name | default ('all') }}"
  become: true
  gather_facts: true
  ignore_unreachable: true
  vars:
    var1: value
    multi_var:
      - value1
      - value2

  roles:
    - role1

  tasks:
    - name: task1
      module:
        param: value1
      notify: handler1

    - name: loop example
      service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'service1', state: 'started' }
        - { name: 'service2', state: 'stopped' }

    - name: debug example
      debug:
        msg: 'This is the output'
        verbosity: 2

    - name: block example
      block:
        - name: task1
      when: ansible_fact == 'value'

  handlers:
    - name: handler1
      module:
        param: value
