---
- name: playbook template
  hosts: "{{ satellite_group_name | default ('all') }}"
  become: true
  gather_facts: true
  ignore_unreachable: true

  vars:
    var1: value
    multi_var:
      - value1
      - value2

  roles:
    - role1

  tasks:
    - name: task1
      module:
        key: value1
      notify: my_handler
      when: ansible_fact == 'value'

    - name: debug example
      debug:
        msg: 'This is the output'
        verbosity: 2

  handlers:
    - name: my_handler
      service:
        name: value
        state: restarted
