---
- hosts: demo
  name: Cleanup demo environment 
  become: yes
  vars:
    httpd_packages:
      - httpd
      - mod_wsgi
  tasks:
    - name: remove site-enabled directory
      file:
        name: /etc/httpd/conf/sites-enabled
        state: absent

    - name: remove httpd.conf
      file: 
        name: /etc/httpd/conf/httpd.conf
        state: absent

    - name: remove index.html
      file:
        name: /var/www/html/index.html
        state: absent
    - name: remove httpd packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items: "{{ httpd_packages }}"
