---
- name: Install and configure Cockpit
  hosts: all

  tasks:
  - name: Install and configure Cockpit
    block:
      - name: Install Cockpit
        yum:
          name: cockpit
          state: latest

      - name: Enable cockpit
        service:
          name: cockpit.socket
          enabled: yes
        notify: restart_cockpit

      - name: Enable firewall rule
        firewalld:
          service: cockpit
          permanent: yes
          immediate: yes
          state: enabled
          offline: yes
        ignore_errors: yes
    when:
      - ansible_distribution == 'RedHat'
      - ansible_distribution_major_version != '6'
  handlers:
    - name: restart_cockpit
      service:
        name: cockpit
        state: restarted
