[all]
centos8
centos8-stream
centos9-stream
debian
fedora
freebsd
opensuse
slackware
ubuntu
ansible-testing.tonneson.home
freenas.tonneson.home
freenas-nfs.tonneson.home
main.tonneson.home
raspberrypi3.tonneson.home
raspberrypi4.tonneson.home
vbox.tonneson.home

[libvirt]
centos8
centos8-stream
centos9-stream
debian
fedora
freebsd
opensuse
slackware
ubuntu

[physical]
freenas.tonneson.home
freenas-nfs.tonneson.home
main.tonneson.home
raspberrypi3.tonneson.home
raspberrypi4.tonneson.home
vbox.tonneson.home

[freebsd-server]
freebsd
freenas.tonneson.home
freenas-nfs.tonneson.home

[raspbian]
raspberrypi3.tonneson.home
raspberrypi4.tonneson.home

[windows]
main.tonneson.home

[fedora-server]
vbox.tonneson.home

[dnf]
centos8
centos8-stream
centos9-stream
fedora

[apt]
debian
ubuntu

[freebsd-update]
freebsd

[zypper]
opensuse

[slackpkg]
slackware
