---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Login to RHVM
      ovirt_auth:
        url: https://rhvm.tonneson.home/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: secret_password
    - name: Set RHVH to maintenance
      ovirt_host:
        auth: "{{ ovirt_auth }}"
        state: maintenance
        name: "{{ item }}"
        wait: yes
      loop:
        - rhvh1.tonneson.home
        - rhvh2.tonneson.home
        - rhvh3.tonneson.home
        - rhvh5.tonneson.home
    - name: Cleanup RHV auth token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
