---
- name: Configure Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aap_configuration_collect_logs: true
    aap_configuration_async_delay: 5
    aap_configuration_loop_delay: 5
    controller_configuration_credentials_loop_delay: 5
    controller_configuration_credentials_async_retries: 50
    controller_configuration_credentials_async_delay: 5
    # Uncomment for debugging secrets
    #controller_configuration_credentials_secure_logging: false

  tasks:
    - name: Load all configuration files
      ansible.builtin.include_vars:
        dir: configs
        extensions:
          - yml
      tags:
        - always

    - name: Configure AAP using dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch

