---
- name: Publish and promote content views
  hosts: "{{ localhost | default ('satellite.tonneson.home') }}"
  gather_facts: no
  ignore_errors: yes

  #vars_files:
    # Contains value for vault_admin_password
    # Commented out when using via Tower/Controller
  #  - admin_password.vault

  vars:
    admin_username: "{{ my_admin_user | default ('admin') }}"
    admin_password: "{{ vault_admin_password }}"
    satellite_host: "{{ my_satellite | default ('satellite.tonneson.home') }}"
    org_to_target: "{{ my_organization | default ('Tonneson Lab') }}"
    default_description: "Monthly - {{ now().strftime('%Y-%m-%d') }}"

  tasks:
    - name: "Promote CCVs in QA (n-2) to Prod"
      redhat.satellite.content_view_version:
        username: "{{ admin_username }}"
        password: "{{ admin_password }}"
        server_url: "https://{{ satellite_host }}"
        content_view: "{{ item }}"
        organization: "{{ org_to_target }}"
        validate_certs: no
        description: "{{ default_description }}"
        current_lifecycle_environment: QA
        lifecycle_environments:
          - Prod
      loop:
        - ccv-RHEL7-plus-SatClient
        - ccv-RHEL8-plus-SatClient
        - ccv-RHEL9-plus-SatClient
        - ccv-RHEL10-plus-SatClient

    - name: "Promote CCVs Dev (n-1) to QA"
      redhat.satellite.content_view_version:
        username: "{{ admin_username }}"
        password: "{{ admin_password }}"
        server_url: "https://{{ satellite_host }}"
        content_view: "{{ item }}"
        organization: "{{ org_to_target }}"
        validate_certs: no
        description: "{{ default_description }}"
        current_lifecycle_environment: Dev
        lifecycle_environments:
          - QA
      loop:
        - ccv-RHEL7-plus-SatClient
        - ccv-RHEL8-plus-SatClient
        - ccv-RHEL9-plus-SatClient
        - ccv-RHEL10-plus-SatClient

    - name: "Publish RHEL CVs so CCVs pick up new version"
      redhat.satellite.content_view_version:
        username: "{{ admin_username }}"
        password: "{{ admin_password }}"
        server_url: "https://{{ satellite_host }}"
        content_view: "{{ item }}"
        organization: "{{ org_to_target }}"
        validate_certs: no
        description: "{{ default_description }}"
        lifecycle_environments:
          - Library
      loop:
        - cv-RHEL7
        - cv-RHEL8
        - cv-RHEL9
        - cv-RHEL10

    - name: "Publish CCVs and promote that version to Dev"
      redhat.satellite.content_view_version:
        username: "{{ admin_username }}"
        password: "{{ admin_password }}"
        server_url: "https://{{ satellite_host }}"
        content_view: "{{ item }}"
        organization: "{{ org_to_target }}"
        validate_certs: no
        description: "{{ default_description }}"
        lifecycle_environments:
          - Library
          - Dev
      loop:
        - ccv-RHEL7-plus-SatClient
        - ccv-RHEL8-plus-SatClient
        - ccv-RHEL9-plus-SatClient
        - ccv-RHEL10-plus-SatClient
