---
- hosts: demo
  name: Remove the apache web service
  become: yes

  tasks:
    - name: stop httpd
      ansible.builtin.service:
        name: httpd
        state: stopped

    - name: remove apache
      ansible.builtin.yum:
        name: httpd
        state: absent


