---
- hosts: demo
  name: Install the apache web service
  become: yes

  tasks:
    - name: install apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: start httpd
      ansible.builtin.service:
        name: httpd
        state: started
