---
- name: Check system services / daemons
  hosts: all
  gather_facts: no

  tasks:
    - name: Checking services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - chronyd
        - crond
        - kdump
        - sshd
        - sssd



