---
- name: System check for vbox
  hosts: localhost
  gather_facts: no

  vars:


  tasks:
    - name: Checking mount points

    - name: Checking services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - chronyd
        - cockpit
        - crond
        - httpd
        - sshd
        - virt-who

    - name: Checking libvirt
      service:
        name: libvirtd
        state: started
      when: "{{ lookup('file', '/root/pause-check-kvm') }}"

    - name: Checking running VMs
