---
controller_credential_types:
- name: Single Secret
  description: Provide secret value to a variable
  inputs:
    fields:
    - type: string
      id: var_secret
      label: Variable Secret
      secret: true
    required:
    - var_secret
  injectors:
    extra_vars:
      secret: !unsafe ""
