---
controller_credentials:
# Source control credentials
- name: My Github Credential
  description: Pulls from my Github repo
  organization: Default
  credential_type: Source Control
  inputs:
    ssh_key_data: "{{ github_ssh_key }}"

# User credentials
- name: Ansible-user SSH Key
  description: User to run most jobs
  organization: Default
  credential_type: Machine
  inputs:
    username: ansible-user
    become_method: sudo
    become_username: root
    ssh_key_data: "{{ ansible_ssh_key }}" 

- name: Root Password Credential
  organization: Default
  credential_type: Machine
  inputs:
    username: root
    password: "{{ secret_root_pw }}"

- name: Raspberry Pi User
  organization: Default
  credential_type: Machine
  inputs:
    username: pi
    password: "{{ secret_rpi_pw }}"
    become_method: sudo
    become_username: root

# Other credentials    
- name: Sat6 Credential for AAP
  description: Used to pull inventory from Satellite
  organization: Default
  credential_type: Red Hat Satellite 6
  inputs:
    host: https://satellite.tonneson.home
    username: ansible-tower
    password: "{{ secret_sat6_pw }}"

