---
- name: "Patch RHEL 6 Servers"
  block:
    - name: "Update packages"
      yum:
        name: "{{ patch_pkgs | default('*') }}"
        state: "latest"
        update_cache: "yes"
      register: "patch_yum_results"
      retries: "3"
      until: "patch_yum_results is succeeded"
      notify:
        - "Reboot RHEL 6 after patching"

    - name: "Output collected yum update output"
      debug:
        var: "patch_yum_results.results"
      when: "patch_display_patch_output"

  when:
    - 'ansible_os_family == "RedHat"'
    - 'ansible_distribution_major_version == "6"'
