---
- name: Create non-root user to run ansible
  hosts: all
  become: yes
  gather_facts: no
  ignore_unreachable: yes

  tasks:
    - name: User ansible-user exists
      ansible.builtin.user:
        name: ansible-user
        uid: 4321
        state: present
        comment: "Ansible user"
        password: $6$sk/Hsd.G$jNGUF7jVtQzZSCr.VB2MWZxdG4bbx2A7afRY6HLZeKh4S0gKGQ5y1MGbQhoW.pgfKcJd6z6znsaIIXXFQwH6m.

    - name: Ensure key is in ansible-user's ~/.ssh/authorized_hosts
      ansible.posix.authorized_key:
        user: ansible-user
        state: present
        key: http://vbox.tonneson.home/pub/ansible-user.key

    - name: Modify sudo config to allow ansible-user sudo without a password
      ansible.builtin.copy:
        content: "ansible-user ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/ansible
        mode: 0440
        owner: root
        group: root
        validate: visudo -cf %s
