---

- name: Create tasks for advisor to flag
  hosts: all
  connection: smart
  gather_facts: false
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: start httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: create index.html
      ansible.builtin.copy:
        content: "This space left blank"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: "Decreased security: httpd serving unencrypted (HTTP) traffic"
      ansible.builtin.uri:
        url: http://localhost/

    - name: "Decreased security: TLS key permissions"
      ansible.builtin.copy:
        content: "this is a test TLS private key"
        dest: /etc/pki/tls/private/test.pem
        mode: '0644'

    - name: "Incorrect permissions on sensitive files"
      ansible.builtin.file:
        path: /etc/passwd
        mode: '0666'

    - name: "Decreased security: OpenSSH config permissions"
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        mode: '0666'

    - name: regenerate insights
      ansible.builtin.command: insights-client
