---
- name: Install and configure Cockpit
  hosts: all

  tasks:
  - name: Install and configure Cockpit
    block:
      - name: Install Cockpit
        ansible.builtin.package:
          name: cockpit
          state: present

      - name: Enable cockpit
        ansible.builtin.service:
          name: cockpit.socket
          enabled: yes
        notify: restart_cockpit

      - name: Enable firewall rule
        ansible.posix.firewalld:
          service: cockpit
          permanent: yes
          immediate: yes
          state: enabled
          offline: yes
        ignore_errors: yes
    when:
      - ansible_distribution == 'RedHat'
      - ansible_distribution_major_version != '6'
  handlers:
    - name: restart_cockpit
      ansible.builtin.service:
        name: cockpit
        state: restarted
