---
- name: "Patch RHEL 6 Servers"
  hosts: all
  vars:
    - patch_display_patch_output: true

  tasks:
    - name: "Patch servers"
      block:
        - name: "Update packages"
          ansible.builtin.package:
            name: "{{ patch_pkgs | default('*') }}"
            state: "latest"
            update_cache: "yes"
          register: "patch_yum_results"
          retries: "3"
          until: "patch_yum_results is succeeded"

        - name: "Output collected yum update output"
          ansible.builtin.debug:
            var: "patch_yum_results.results"
          when: "patch_display_patch_output"
      when:
        - 'ansible_os_family == "RedHat"'
        - 'ansible_distribution_major_version == "6"'
