---
- name: "Set of tasks to patch systems"
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: "Patch systems that work with package"
      ansible.builtin.package:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: "Patch FreeBSD"
      community.general.pkgng:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "FreeBSD"
      
    - name: "Patch SuSE"
      community.general.zypper:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "Suse"

    - name: "Patch Slackware"
      block:
#        - name: "Run slackpkg update"
#          ansible.builtin.shell:
#            cmd: slackpkg update
#        - name: "Run slackpkg install-new"
#          ansible.builtin.shell:
#            cmd: slackpkg install-new
#        - name: "Run slackpkg upgrade-all"
#          ansible.builtin.shell:
#            cmd: slackpkg upgrade-all
#        - name: "Run slackpkg clean-system"
#          ansible.builtin.shell:
#            cmd: slackpkg clean-system
#        - name: "Run LILO to update boot"
#          ansible.builtin.shell:
#            cmd: lilo
        - name: "Slackware kinda sucks."
          ansible.builtin.debug:
            msg: "Slackware does not support unattended upgrades."
      when: ansible_facts['os_family'] == "Slackware"
    
    - name: "Reboot system"
      ansible.builtin.reboot:

    - name: "Validate update, output OS version"
      ansible.builtin.debug:
        msg: "OS version: {{ ansible_distribution }} {{ ansible_distribution_version }}"

