---
- name: "Set of tasks to patch systems"
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: "Patch RHEL-based systems"
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: "Reboot system"
      ansible.builtin.reboot:

    - name: "Validate update, output OS version"
      ansible.builtin.debug:
        msg: "OS version: {{ ansible_distribution }} {{ ansible_distribution_version }}"

