---
- name: "Start libvirt machine(s)"
  hosts: vbox
  become: yes
  gather_facts: no

  tasks:
  - name: start vm
    community.libvirt.virt:
      name: "{{ vm_to_start }}"
      state: running
      uri: "{{ libvirt_uri | default ('qemu:///system') }}"

  - name: "Ensure system is up via port 22"
    ansible.builtin.wait_for:
      host: "{{ inventory_hostname }}"
      port: "{{ ssh_port }}"
      delay: 10
      timeout: 300
      state: started

- name: "Set of tasks to patch systems"
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: "Patch RHEL-based systems"
    ansible.builtin.package:
      name: '*'
      state: latest
    when: 

  - name: "Reboot system"
    ansible.builtin.reboot:

  - name: "Validate update, output OS version"

- name: "Stop libvirt machine(s)"
  hosts: vbox
  become: yes
  gather_facts: no

  tasks:
  - name: Stop vm
    community.libvirt.virt:
      name: "{{ vm_to_start }}"
      state: shutdown
      uri: "{{ libvirt_uri | default ('qemu:///system') }}"
