---
- name: Public key is deployed to hosts
  hosts: all
  ignore_unreachable: True
  gather_facts: no
  vars:
    key_user: root
    key_file: ~/.ssh/id_rsa.pub

  tasks:
    - name: Ensure key is in {{ key_user}} ~/.ssh/authorized_hosts
      ansible.posix.authorized_key:
        user: '{{ key_user }}'
        state: present
        key: '{{ key_file }}'
