---
- name: "Control libvirt machine"
  hosts: all 
  gather_facts: no

  tasks:
    - name: Change VM state 
      community.libvirt.virt:
        name: "{{ item }}"
        state: "{{ vm_state | default ('running') }}"
      register: vm_state_results
      until: "vm_state_results is success"
      retries: 5
      delay: 2
      loop: "{{ groups['group_to_control'] }}"
