---
- name: "Start libvirt machine"
  hosts: "{{ satellite_group_name | default ('vbox') }}"
  become: yes
  gather_facts: no

  tasks:
  - name: start vm
    community.libvirt.virt:
      name: "{{ vm_to_start }}"
      state: "{{ vm_state | default ('running' }}"
      uri: "{{ libvirt_uri | default ()'qemu:///system') }}"
